# Generated by Django 3.2.9 on 2021-11-19 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Recipe',
        ),
    ]
