# Generated by Django 3.2.9 on 2021-11-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_course_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='price',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
